/*
     Copyright (C) 2004-2013 JoomlArt.com. All Rights Reserved.
 @license       GNU General Public License version 2 or later; see LICENSE.txt
 @authors       JoomlArt, JoomlaBamboo, (contribute to this project at github
                & Google group to become co-author)
 @Google group: https://groups.google.com/forum/#!forum/t3fw
 @Link:         http://t3-framework.org
------------------------------------------------------------------------------
*/
jQuery(document).ready(function(a){/MSIE\s([\d.]+)/.test(navigator.userAgent)&&10>new Number(RegExp.$1)?a("html").addClass("old-ie"):/constructor/i.test(window.HTMLElement)&&a("html").addClass("safari");var d=a("body"),e=a(".t3-wrapper"),q=a(".off-canvas-toggle"),m=a(".t3-off-canvas"),r=a(".t3-off-canvas .close"),h=null,k=null,f="left",n=null;if(d.length){q.each(function(){var b=a(this),c=a(b.data("nav")),g=b.data("effect");b="rtl"==a("html").attr("dir")&&"right"!=b.data("pos")||"rtl"!=a("html").attr("dir")&&
"right"==b.data("pos")?"right":"left";c.addClass(g).addClass("off-canvas-"+b);-1==a.inArray(g,["off-canvas-effect-3","off-canvas-effect-16","off-canvas-effect-7","off-canvas-effect-8","off-canvas-effect-14"])?e.before(c):e.prepend(c)});q.on("tap",function(b){p(b);if(d.hasClass("off-canvas-open"))return l(b),!1;h=a(this);k=a(h.data("nav"));n=e.find("*").filter(function(){return"fixed"===a(this).css("position")});k.addClass("off-canvas-current");f="rtl"==a("html").attr("dir")&&"right"!=h.data("pos")||
"rtl"!=a("html").attr("dir")&&"right"==h.data("pos")?"right":"left";m.height(a(window).height());if((b=a(window).data("events"))&&b.scroll&&b.scroll.length){for(var c=[],g=0;g<b.scroll.length;g++)c[g]=b.scroll[g].handler;a(window).data("scroll-events",c);a(window).off("scroll")}b=a("html").scrollTop()?a("html").scrollTop():a("body").scrollTop();a("html").addClass("noscroll").css("top",-b).data("top",b);a(".t3-off-canvas").css("top",b);n.each(function(){for(var b=a(this),c=b.parent();!c.is(e)&&"static"===
c.css("position");)c=c.parent();c=-c.offset().top;b.css({position:"absolute","margin-top":c})});d.scrollTop(b);d[0].className=d[0].className.replace(/\s*off\-canvas\-effect\-\d+\s*/g," ").trim()+" "+h.data("effect")+" off-canvas-"+f;setTimeout(t,50);return!1});var t=function(){d.addClass("off-canvas-open");e.on("click",l);r.on("click",l);m.on("click",p);if(a.browser.msie&&10>a.browser.version){var b={},c={};b["padding-"+f]=a(".t3-off-canvas").width();c[f]=0;e.animate(b);k.animate(c)}},l=function(){e.off("click",
l);r.off("click",l);m.off("click",p);setTimeout(function(){d.removeClass("off-canvas-open")},100);setTimeout(function(){d.removeClass(h.data("effect")).removeClass("off-canvas-"+f);d.scrollTop(0);a("html").removeClass("noscroll").css("top","");a("html,body").scrollTop(a("html").data("top"));k.removeClass("off-canvas-current");n.css({position:"","margin-top":""});if(a(window).data("scroll-events")){for(var b=a(window).data("scroll-events"),c=0;c<b.length;c++)a(window).on("scroll",b[c]);a(window).data("scroll-events",
null)}},550);if(a("html").hasClass("old-ie")){var b={},c={};b["padding-"+f]=0;c[f]=-a(".t3-off-canvas").width();e.animate(b);k.animate(c)}},p=function(a){a.stopPropagation();return!0}}});